In [268]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt

In [364]:
class Circuit:
    def __init__(self,n):
        self.n = n
        self.wires = [Wire(k) for k in range(n)]
        self.gates = []
        
    def addGate(self,g):
        self.gates.append(g)
        for bit in g.bits:
            self.wires[bit].addGate(g)
    
    def __str__(self):
        string = ""
        for gate in self.gates:
            string = string + str(gate)
            
        return string
        
    def hamiltonian(self):
        ham = None
        for gate in self.gates:
            print("hello")
            if ham == None:
                ham = gate.hamiltonian(self.n)
                print(ham)
            else:
                ham = np.dot(gate.hamiltonian(self.n) * ham)
        return ham
    
    
    def printWires(self):
        for wire in self.wires:
            print(wire)
        
class Wire:
    def __init__(self,k):
        self.k = k
        self.gates = []
    
    def addGate(self,g):
        self.gates.append(g)
    
    def removeLastGate(self):
        return self.gates.pop()
    
    def __str__(self):
        string = f"[{self.k}]:"
        for gate in self.gates:
            string += str(gate)
        return string

class Gate:
    #assumes if bits = (0,1,2), order is kron(b2,b1,b0).  This follows from c01 gate having control
    #on 0 and target on 1 by convention
    gatecount = 0

    def __init__(self,matrix,bits):
        assert(matrix.shape == (2**len(bits),2**len(bits)))
        self.matrix = matrix
        self.bits = bits
        self.id = Gate.gatecount
        Gate.gatecount += 1
        
    def __str__(self):
        return f"-g{self.id}-"
    
    def hamiltonian(self,n):
        #first construct hamiltonian operating on first len(bits) qubits, then swap
        ham = self.matrix
        for i in range(1 - len(self.bits)):
            ham = np.kron([[1,0],[0,1]],ham)
        return ham
    def _swapcircuit(self,n):
        for i in range(len(bits)):
            pass
            
        
            



In [365]:
circ = Circuit(2)

In [366]:
C01 = Gate(np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]]),(0,1))

In [367]:
C01.matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [368]:
circ.addGate(C01)

In [369]:
print(str(circ))

-g0-


In [370]:
circ.wires[1]

In [371]:
str(circ.wires[0])

'[0]:-g0-'

In [372]:
circ.printWires()

[0]:-g0-
[1]:-g0-


In [373]:
np.kron([1,0],[1,0])

array([1, 0, 0, 0])

In [374]:
x = np.array([[0,1],[1,0]])
np.dot(x,x)

array([[1, 0],
       [0, 1]])

In [375]:
def test_swap_alg(targs,n):
    targs = np.array(targs)
    tmpls = [i for i in range(n)]
    end = np.setdiff1d(tmpls,targs)
    ls = np.concatenate((targs,end))
    return ls

In [376]:
print(test_swap_alg([3,1], 5))

[3 1 0 2 4]


In [377]:
targs = [1, 3,4]
ls = [i for i in range(10)]

ls[targs in ls]

0

In [378]:
print(circ.hamiltonian())

hello
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
